### ISSUE TITLE
Missing properties in `OrderItemResponse` response model

### ISSUE THREAD

**Issue by petro-dutchak-infopulse** [voucherifyio/voucherify-java-sdk#126]
From what we can observe some properties available in live response are not neither in SDK nor on `docs.voucherify.io/reference`.

For example, live response contains fields of `OrderItemResponse` from voucher validation response:
- `subtotal_amount` : missing in SDK and in `docs`
- `applied_discount_amount`: missing in SDK however is available in `docs`.

There are might be other missing properties in this and in other models, would be good to do an update of SDK according to the latest engine.

Thanks!

**Comment by jkaliszuk** [comment]
Thanks for Your report. Currently our latest docs version should be up to date. Nonetheless SDK is not. I already added all the missing properties to `OrderResponse` and `OrderItemResponse`. The changes will be released in next version (probably next week).
