### ISSUE TITLE
Missing percentOff in DiscountResponse 

### ISSUE THREAD

**Issue by mariaivanova-git** [voucherifyio/voucherify-java-sdk#149]
Hello,
Our application uses the Validations APIs via ValidationsModule and intends to migrate to the StackableModule for client access to Validate Stackable Discounts API, as the aforementioned is deprecated. I came to the following issue while evaluating this possibility:

io.voucherify.client.DiscountResponse lacks mapping for **percent_off** field, while a ValidateStackableDiscountResponse can look like this:

            "result": {
                "discount": {
                    "type": "PERCENT",
                    "effect": "APPLY_TO_ITEMS",
                    "percent_off": 10,
                    "is_dynamic": false
                }
            }

This prevents us from obtaining the predefined discount of percent vouchers and as a result from migrating our app to the new APIs.

Do you think it would be possible to apply this small change?

**Comment by jkaliszuk** [comment]
Hi @mariaivanova-git,
We've just released the 11.2.1 version with the requested changes. It should be available in the maven/gradle repositories within few hours.

**Comment by mariaivanova-git** [comment]
@jkaliszuk, thank you for apply the fix!
