### ISSUE TITLE
Get Customers List

### ISSUE THREAD

**Issue by fabricelepro** [voucherifyio/voucherify-java-sdk#46]
Hi, i'm implementing this on my project, and i was searching out to test if user exist by the "Email" and i found that you haven't implement the "Get Customer List" with the filters.

**Comment by lkulig** [comment]
Hey @fabricelepro thanks for feedback. We will do our best to provide you with the missing functionality by the end of this week, is it suitable for you?

**Comment by fabricelepro** [comment]
No problem. Or you can't provide how to run the project on dev so i can i make "Pull Request"

**Comment by lkulig** [comment]
@fabricelepro sorry for late response. Last sunday we released version `5.3.0` which contains missing methods. If there's any problems, please drop us a note :)
