### ISSUE TITLE
PublishVoucherResponse contains all null fields however the voucher is created on Voucherify successfully

### ISSUE THREAD

**Issue by asadyarkhan007** [voucherifyio/voucherify-java-sdk#50]
```
 PublishVoucher publishVoucher = PublishVoucher.builder().campaign(referralCampaignName).customer(customer).build();
        return voucherify.distributions().publish(publishVoucher);

```
When I execute the above code the Referral Campaign voucher is created but the response object PublishVoucherResponse is empty object means it contains all fields as null.

**Comment by asadyarkhan007** [comment]
Hi,
I am block, Kindly fix this issue.

**Comment by lkulig** [comment]
hey @asadyarkhan007, PR (#51) with appropriate changes is ready, new version will be released today

**Comment by asadyarkhan007** [comment]
Thanks.
