### ISSUE TITLE
Product model missing a price variable

### ISSUE THREAD

**Issue by stevenkhong** [voucherifyio/voucherify-java-sdk#57]
`Product.price` and `ProductBuilder.price(Integer)`

If they are intentionally left out, I cant seem to find another way to update the `price` of a `Product` through other APIs.

Any help greatly appreciated.

**Comment by lkulig** [comment]
Hey @stevenkhong I'll take a look at this asap and will keep you updated :)

**Comment by lkulig** [comment]
@stevenkhong version `6.0.3` was released just now, soon it should be available in the mvn repository

**Comment by stevenkhong** [comment]
@lkulig Just updated to `6.0.3` and tested out the fix. Thanks for the prompt action!
