### ISSUE TITLE
voucher rules does not return from java SDK

### ISSUE THREAD

**Issue by asadyarkhan007** [voucherifyio/voucherify-java-sdk#63]
Hi,
We are your paid customers, We are working on an application where we need to get the voucher's rules(metadata) against voucher code.
It's perfectly return on getting the voucher code from RESTAPI mentioned below:
https://api.voucherify.io/v1/vouchers/code

However we have integrated your Java SDK as we found it easy for other stuff but now we are stuck when we try to get the voucher detail it does not return voucher rules.

Following is the response hierarchy that does return in rest API call.

  "validation_rules": {
     redemptions:{
            "metadata": {
                       "RULE1": {
                   }
             }
    }
}

We need all the defined rules using this Java SDK.
we are using voucherify-java-sdk:6.0.4

**Comment by lkulig** [comment]
Hey @asadyarkhan007 new version was released recently, it might take a while for new version to be available in maven repositories. After verifying and if everything works please close the issue.

**Comment by asadyarkhan007** [comment]
ok I will do after verifying as still in maven repo 6.0.4 is showing.

**Comment by asadyarkhan007** [comment]
Thanks its done in 6.0.5
