### ISSUE TITLE
VoucherValidationResponse no longer contains Type property

### ISSUE THREAD

**Issue by asadyarkhan007** [voucherifyio/voucherify-java-sdk#65]
Hi, 
I was using version 6.0.1 there was property "Type" in VoucherValidationResponse. Now I am using 6.0.5 but this property has been removed and my application crashing can you guys fix it as this property is present in other Response Model like VoucherResponse & PublishVoucherResponse etc.

Kindly fix this..

**Comment by lkulig** [comment]
@asadyarkhan007 This property was never returned from the Voucher Validation API, meaning you would always get `null` for VoucherType in `VoucherValidationResponse`. The reason it was available in `VoucherValidationResponse` was a clear overlook on our side. I suggest that you remove it from your code as it makes no sense to put it back into SDK.
