### ISSUE TITLE
OrderResponse missing discount_amount

### ISSUE THREAD

**Issue by vsr625** [voucherifyio/voucherify-java-sdk#82]
Hi, why isn't the discount_amount field not present in the OrderResponse model, this field was present in older versions of the sdk, why was it removed in the newer version? and how would one access the discount amount for a normal redemption using the RedemptionResponse model?

**Comment by lkulig** [comment]
Hey @vsr625 the `discount_amount` was removed accidentally in the previous releases, this is clearly an overlook on our side. It will be restored with new release. As for the RedemptionResponse the only way to get it is via the `OrderResponse` property of that model, without providing `Order` during redemption the only way to access it is via `voucher` object in RedemptionResponse.

**Comment by vsr625** [comment]
Thanks of the response @lkulig , I would greatly appreciate it if this change is done sooner. Thanks!

**Comment by lkulig** [comment]
@vsr625 version `7.4.1` (with fix) was released, so it should be available soon on maven central. For now I will close this issue, if you have any further problems please create a new issue. If you use `sonatype` as an additional maven repo then you can already download the newest version [here](https://oss.sonatype.org/service/local/repositories/releases/content/io/voucherify/client/voucherify-java-sdk/7.4.1/voucherify-java-sdk-7.4.1.jar)
