### ISSUE TITLE
getQualifiedMethod - sorting params

### ISSUE THREAD

**Issue by tpindel** [voucherifyio/voucherify-java-sdk#89]
Could you add support for the parameter order (Sorts the results, options: created_at, -created_at, updated_at, -updated_at) in the `getQualifiedMethod`?

One of the users tried to pass the parameter via QualifiedResourceFilter, however, it seems it only takes the audienceRulesOnly and Limit.

**Comment by lkulig** [comment]
implemented in #90 released in `8.1.0`
