### ISSUE TITLE
PromotionValidationResponse tracking_id return json

### ISSUE THREAD

**Issue by wilfredchen** [voucherifyio/voucherify-java-sdk#91]
Promotion Validation Response tracking_id returning a json object but the datatype is set to String under the PromotionValidationResponse.class in the sdk.

I keep getting this error message attached below every time I try to call PromotionValidationResponse.

![Screen Shot 2020-07-14 at 09 43 03](https://user-images.githubusercontent.com/46327334/87370806-87209280-c5b6-11ea-9f62-f57024ca977e.png)

**Comment by lkulig** [comment]
@wilfredchen this should also be fixed in version `9.1.1`. Closing for now.
