### ISSUE TITLE
Cannot seem to set reward points from redeem

### ISSUE THREAD

**Issue by wilfredchen** [voucherifyio/voucherify-java-sdk#92]
The SDK doesn't seem to have a way to specify the amount of reward point that I want to redeem as shown in the api.

![Screen Shot 2020-07-14 at 09 50 42](https://user-images.githubusercontent.com/46327334/87371240-80dee600-c5b7-11ea-90d0-ea38d9c22aba.png)

**Comment by lkulig** [comment]
@wilfredchen new version 9.1.0 (which should be available in maven repo soon) will give you the possibility to specify points when redeeming loyalty card. If you encounter any issue with that then please create a new issue. Closing this for now.
