### ISSUE TITLE
Cannot link v9.1.0 from maven

### ISSUE THREAD

**Issue by wilfredchen** [voucherifyio/voucherify-java-sdk#95]
The dependancy when linked from maven are empty so I extracted the jar file and found that there are .java file in it instead of .class

![image](https://user-images.githubusercontent.com/46327334/88148349-0c4c1d00-cc31-11ea-80a9-61cc06049c57.png)

![image](https://user-images.githubusercontent.com/46327334/88148363-10783a80-cc31-11ea-9a88-81140abbd506.png)

**Comment by lkulig** [comment]
@wilfredchen issue is described and fixed with PR #96. New version `9.1.1` should be available on maven repo soon. Closing for now.
